version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "8042:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "15306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      
volumes:
  dbdata:
